config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "foods#index"

  # resources :public_recipes, only: [:index]
  # resources :general_shopping_list, only: [:show]

  get  'public_recipes', to: 'recipes#public_recipes'
  get  'general_shopping_list', to: 'foods#shopping_list'

  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :new, :show, :public, :create, :destroy] do
    resources :recipe_foods, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :foods
  end

  resources :users do
    resources :recipes
    resources :foods
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:

    user ||= User.new

    can :read, Recipe do |recipe|
      recipe.user == user || recipe.public
    end

    can [:update, :destroy], Recipe do |recipe|
      recipe.user == user
    end

    can :manage, Food, user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy

  # validations
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  # validations
  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true, length: { minimum: 4 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  # validations
  validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 1_000_000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  :confirmable, :lockable, :trackable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  # validations
  validates :name, presence: true, allow_blank: false, length: { in: 1...50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_out_path_for(_resource_or_scope)
    request.referrer
    '/users/sign_in'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password)
    end

    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password, :remember_me)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # before_action :set_food, only: i%[edit update destroy]

  def index
    @foods = Food.all.includes(:user)
  end

  def new
    @food = Food.new
  end

  def shopping_list
    @foods = Food.includes(:recipe_foods, :user).where(recipe_foods: { food_id: nil })
    @food_count = @foods.length
    @sum = amount_total(@foods)
  end

  def edit; end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    if @food.save
      redirect_to root_path, notice: 'Food added successfully'
    else
      render :new, alert: 'Food not successfully added'
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food successfuly updated.' }
      else
        format.html { render :edit, status: :unprecessable_entity }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    if @food.destroy
      redirect_to root_path, notice: 'Recipe successfully deleted'
    else
      render :new
    end
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end

  def amount_total(obj)
    sum = 0
    obj.each do |value|
      cost_value = value.price * value.quantity.to_i
      sum += cost_value
    end
    sum
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  # before_action :set_recipe_food, only: %i[edit update destroy]

  def index
    @recipe_foods = RecipeFood.all
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  def edit
    @recipe = RecipeFood.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_food_params)
    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to @recipe, notice: 'Recipe food was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    respond_to do |format|
      format.html { redirect_to @recipe, notice: 'Recipe food was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all.includes(:user)
  end

  def public_recipes
    @public_recipes = Recipe.includes(%i[user foods recipe_foods]).where(public: true).order(created_at: :desc)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    # @foods = @recipe.recipe_foods.includes(:food).all
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe successfully deleted'
    else
      render :new
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe added successfully'
    else
      render :new, alert: 'Recipe not successfully added'
    end
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  def total_cost(recipe)
    recipe.foods.map do |ingredient|
      ingredient.price.to_i
    end
  end

  def total_quantity(recipe)
    recipe.recipe_foods.map(&:quantity)
  end

  def total_recipy_food(arrays)
    total = 0
    arrays.each do |array|
      total += array[0] * array[1]
    end
    total
  end
  helper_method :total_cost, :total_quantity, :total_recipy_food
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="food-wrapper">
  <div class="add-button-wrapper">
    <%= link_to "Add food", new_food_path, class: "food-remove-btn"%>
  </div>

  <table class="table table-striped my-5 container foodTable">
    <thead>
      <tr> 
        <th scope="col">Food</th>
        <th scope="col">Measurement Unit</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <%if current_user == food.user%>
          <tr>
            <td><%= food.name%></td>
            <td><%= food.measurement_unit%></td>
            <td>$<%= food.price%></td>
            <td><%= button_to 'DELETE', food_path(id: food.id), method: :delete, class: "deleteFood" %></td>  
          </tr>
        <% end %>
      <%end%>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="wrapper-container">
  <h2>Add New Food</h2>
  <%= form_with model: @food, url: foods_path, method: :post do |f| %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Name' %>
    </div>

    <div class="field">
      <%= f.label :measurement_unit %><br />
      <%= f.text_field :measurement_unit, autofocus: true, autocomplete: "name", placeholder: 'measurement unit' %>
    </div>

    <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price, autofocus: true, autocomplete: "name", placeholder: 'Price' %>
    </div>

    <div class="field">
      <%= f.label :quantity %><br />
      <%= f.text_field :quantity, autofocus: true, autocomplete: "name", placeholder: 'Quantity' %>
    </div>

    <div class="actions">
      <%= f.submit "Adding Food", class: "btn-food" %>
    </div>
  <% end %>
</div>

app/views/foods/shopping_list.html.erb
<div class='wrapper-flex recipe-details'>
  <h2 class="header-center-self">Shopping List</h2>
  <div class='shopping_list flex'>
    <p>Amount of food items to buy:<span> <strong><%= @food_count %></strong></span></p>
    <p>Total value of item needed:<span> <strong>$ <%= @sum %></strong></span></p>
  </div>

  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
         <%#if current_user == food.user%>
          <tr>
            <td> <%= food.name %> </td>
            <td> <%= food.quantity %>   <%= food.measurement_unit  %></td>
            <td> $ <%= food.price * food.quantity.to_i %> </td>  
          </tr>
         <%#end%>
      <% end %>
    </tbody>
  </table>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if user_signed_in? %>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand">Logged as : <%= current_user.name %></a>
        <div class="d-flex">
          <%= link_to "Foods", foods_path, class: " nav-link active" %>
          <%= link_to "Recipe List", recipes_path, class:" nav-link" %>
          <%= link_to "Public Recipe List", public_recipes_path, class: "nav-link" %>
          <%= link_to "Edit User", edit_user_registration_path, class: "btn btn-outline-success" %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-success" %>
        </div>
      </div>
    </nav>
    <% else %>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand">My Recipe</a>
        <form class="d-flex">
          <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-success" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success" %>
        </form>
      </div>
    </nav>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

 <%= form_with  model: @recipe, url: { action: "update" }, local: true  do |form|%>

   <div class="form-box">
      <%= form.label :food_id, class:"label" %><br>
      <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: false} , class:"field" %><br>
    </div>
  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/index.htm.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <div>
      <p>
        <strong>Quantity:</strong>
        <%= recipe_food.quantity %>
      </p>
    </div>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>New recipe food</h1>

<%= form_with model: [@recipe, @recipe.recipe_foods.build] do |form| %>
  <% if @recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% @recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-box">
      <%= form.label :food_id, class:"label" %><br>
      <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: false} , class:"field" %><br>
    </div>
  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity,  min: 1 %>
  </div>

  <div>
    <%= form.submit "Adding recipe" %>
  </div>
<% end %>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%#= render @recipe_food %>

<div>
  <%#= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%#= link_to "Back to recipe foods", recipe_foods_path %>
  <%#= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>

app/views/recipes/index.html.erb
<div class="wrapper">
    <h1 id="recipe-headline">Recipes List</h1>
    <div><%= link_to "Add recipe", new_recipe_path, class: "add-recipe-btn" %></div>

  <% if @recipes.empty? %>
    <h2>There are no recipes yet!!</h2>
  <% else %>
    <% @recipes.each do |recipe| %>
      <% if can? :read, recipe %>
        <div class="recipe-container">
          <div class="recipe-name-remove-btn">
            <%= link_to recipe, class: 'link-to-rec' do %>
              <p class="recipe-name"><%= recipe.name %></p>
            <% end %>
            <%if current_user == recipe.user  %>
              <%= button_to "Delete", recipe_path(id: recipe.id), method: :delete, class: "remove-btn" %>
            <% end %>
          </div>
          <div class="description"><%= recipe.description %></div>
        </div>
      <% end %>

    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="wrapper-container">
  <h2>Add new recipe</h2>
  <%= form_with model: @recipe, url: recipes_path, method: :post do |f| %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :preparation_time %><br />
      <%= f.text_field :preparation_time, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :cooking_time %><br />
      <%= f.text_field :cooking_time, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :public %><br />
      <%= f.check_box :public, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="actions">
      <%= f.submit "Adding recipe", class: "btn-recipe" %>
    </div>
  <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="public-recipes-wrapper" style="margin: auto; width: 50%; ">
    <h2>Public Recipes</h2>
    <% @public_recipes.each do |recipe| %>
      <a href = "<%= recipe_path(recipe) %>" class="public flex" style="text-decoration: none; color: black;">
        <div class="card mb-3" style="width: 100%; padding: 8px;">
          <div class="row g-0" style="justify-content: space-evenly">
            <div class="col-md-4">
              <p class = "card-text"><%=recipe.name%></p>
              <p class = "card-text" >By <%=recipe.user.name%></p>
            </div>
            <div class="col-md-4">
              <div class="card-body">
                <p class="card-text">Total food item: <%=recipe.foods.size%> </p>
                <p class="card-text">Total food price: <%=total_recipy_food( total_cost(recipe).zip(total_quantity(recipe)) )%>  </p>
              </div>
            </div>
          </div>
        </div>
      </a>
    <% end %>
</div>

app/views/recipes/show.html.erb
<div class="wrapper-recipe-show">
  <h1 class="title-header"><%= @recipe.name %></h1>
  <div class="top-features">
    <span class="preparation-time">Preparation time: <%= @recipe.preparation_time %> hour</span>
    <div>
      <% if @recipe.public? %>
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
          <label class="form-check-label" for="flexSwitchCheckChecked">Public</label>
        </div>
      <% else %>
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
          <label class="form-check-label" for="flexSwitchCheckDefault">Private</label>
        </div>
      <% end %>
    </div>
  </div>
  <p class="cooking-time">Cooking time: <%= @recipe.cooking_time %> hours</p>
  <p class="steps">Steps go here...</p>

  <% if current_user == @recipe.user %>
    <div class="tools">
      <%= link_to "Generate shopping list", general_shopping_list_path(id: @recipe.id), class: "generate-shopping-list" %>
      <%= link_to "Add ingredients", new_recipe_recipe_food_path(@recipe), class: "add-ingredients-btn" %>
    </div>
  <% else %>
    <div class="tools">
      <%= link_to "Generate shopping list", class: "disable-tool" %>
      <%= link_to "Add ingredients", class: "disable-tool" %>
    </div>
  <% end %>
  <span class="line"></span>

  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %></td>
        <td>$ <%= recipe_food.quantity * recipe_food.food.price %></td>
        <td class="td-button">
            <%if current_user == recipe_food.food.user  %>
              <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food), data: {turbo: false}, method: :update, class: "btn btn-outline-secondary " %> 
              <%= button_to "Delete", recipe_recipe_food_path(recipe_id: recipe_food.recipe_id, id: recipe_food.id), data: {turbo: false}, method: :delete, class: "btn btn-outline-danger" %>
            <% end %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>